package com.tcbuen.pqrs.modelo;
// Generated 20-ago-2014 23:05:43 by Hibernate Tools 4.0.0



/**
 * AnxsXArea generated by hbm2java
 */
public class AnxsXArea  implements java.io.Serializable {


     private Long idAnxXArea;
     private AnexosPqr anexosPqr;
     private AreasInvolucradas areasInvolucradas;
     private String esObligatorio;

    public AnxsXArea() {
    }

    public AnxsXArea(Long idAnxXArea, AnexosPqr anexosPqr, AreasInvolucradas areasInvolucradas, String esObligatorio) {
       this.idAnxXArea = idAnxXArea;
       this.anexosPqr = anexosPqr;
       this.areasInvolucradas = areasInvolucradas;
       this.esObligatorio = esObligatorio;
    }
   
    public Long getIdAnxXArea() {
        return this.idAnxXArea;
    }
    
    public void setIdAnxXArea(Long idAnxXArea) {
        this.idAnxXArea = idAnxXArea;
    }
    public AnexosPqr getAnexosPqr() {
        return this.anexosPqr;
    }
    
    public void setAnexosPqr(AnexosPqr anexosPqr) {
        this.anexosPqr = anexosPqr;
    }
    public AreasInvolucradas getAreasInvolucradas() {
        return this.areasInvolucradas;
    }
    
    public void setAreasInvolucradas(AreasInvolucradas areasInvolucradas) {
        this.areasInvolucradas = areasInvolucradas;
    }
    public String getEsObligatorio() {
        return this.esObligatorio;
    }
    
    public void setEsObligatorio(String esObligatorio) {
        this.esObligatorio = esObligatorio;
    }




}


