package com.tcbuen.pqrs.modelo;
// Generated 20-ago-2014 23:05:43 by Hibernate Tools 4.0.0



/**
 * AnxsXTpSol generated by hbm2java
 */
public class AnxsXTpSol  implements java.io.Serializable {


     private Long idAnexoXTpSol;
     private TipoSolicitudPqr tipoSolicitudPqr;
     private AnexosPqr anexosPqr;
     private String esObligatorio;

    public AnxsXTpSol() {
    }

    public AnxsXTpSol(Long idAnexoXTpSol, TipoSolicitudPqr tipoSolicitudPqr, AnexosPqr anexosPqr, String esObligatorio) {
       this.idAnexoXTpSol = idAnexoXTpSol;
       this.tipoSolicitudPqr = tipoSolicitudPqr;
       this.anexosPqr = anexosPqr;
       this.esObligatorio = esObligatorio;
    }
   
    public Long getIdAnexoXTpSol() {
        return this.idAnexoXTpSol;
    }
    
    public void setIdAnexoXTpSol(Long idAnexoXTpSol) {
        this.idAnexoXTpSol = idAnexoXTpSol;
    }
    public TipoSolicitudPqr getTipoSolicitudPqr() {
        return this.tipoSolicitudPqr;
    }
    
    public void setTipoSolicitudPqr(TipoSolicitudPqr tipoSolicitudPqr) {
        this.tipoSolicitudPqr = tipoSolicitudPqr;
    }
    public AnexosPqr getAnexosPqr() {
        return this.anexosPqr;
    }
    
    public void setAnexosPqr(AnexosPqr anexosPqr) {
        this.anexosPqr = anexosPqr;
    }
    public String getEsObligatorio() {
        return this.esObligatorio;
    }
    
    public void setEsObligatorio(String esObligatorio) {
        this.esObligatorio = esObligatorio;
    }




}


