package com.tcbuen.pqrs.modelo;
// Generated 20-ago-2014 23:05:43 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * InfoSolicitante generated by hbm2java
 */
public class InfoSolicitante  implements java.io.Serializable {


     private Long idInfoSolicitante;
     private TipoDocumento tipoDocumento;
     private String numeroIdentificacion;
     private String nombreEmpresa;
     private String nombreContacto;
     private String correoElectronico;
     private String numeroCelular;
     private String telefonoFijo;
     private Set<SolicitudPqr> solicitudPqrs = new HashSet<SolicitudPqr>(0);

    public InfoSolicitante() {
    }

	
    public InfoSolicitante(Long idInfoSolicitante, TipoDocumento tipoDocumento, String numeroIdentificacion, String nombreContacto, String correoElectronico) {
        this.idInfoSolicitante = idInfoSolicitante;
        this.tipoDocumento = tipoDocumento;
        this.numeroIdentificacion = numeroIdentificacion;
        this.nombreContacto = nombreContacto;
        this.correoElectronico = correoElectronico;
    }
    public InfoSolicitante(Long idInfoSolicitante, TipoDocumento tipoDocumento, String numeroIdentificacion, String nombreEmpresa, String nombreContacto, String correoElectronico, String numeroCelular, String telefonoFijo, Set<SolicitudPqr> solicitudPqrs) {
       this.idInfoSolicitante = idInfoSolicitante;
       this.tipoDocumento = tipoDocumento;
       this.numeroIdentificacion = numeroIdentificacion;
       this.nombreEmpresa = nombreEmpresa;
       this.nombreContacto = nombreContacto;
       this.correoElectronico = correoElectronico;
       this.numeroCelular = numeroCelular;
       this.telefonoFijo = telefonoFijo;
       this.solicitudPqrs = solicitudPqrs;
    }
   
    public Long getIdInfoSolicitante() {
        return this.idInfoSolicitante;
    }
    
    public void setIdInfoSolicitante(Long idInfoSolicitante) {
        this.idInfoSolicitante = idInfoSolicitante;
    }
    public TipoDocumento getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(TipoDocumento tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public String getNumeroIdentificacion() {
        return this.numeroIdentificacion;
    }
    
    public void setNumeroIdentificacion(String numeroIdentificacion) {
        this.numeroIdentificacion = numeroIdentificacion;
    }
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public String getNombreContacto() {
        return this.nombreContacto;
    }
    
    public void setNombreContacto(String nombreContacto) {
        this.nombreContacto = nombreContacto;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getNumeroCelular() {
        return this.numeroCelular;
    }
    
    public void setNumeroCelular(String numeroCelular) {
        this.numeroCelular = numeroCelular;
    }
    public String getTelefonoFijo() {
        return this.telefonoFijo;
    }
    
    public void setTelefonoFijo(String telefonoFijo) {
        this.telefonoFijo = telefonoFijo;
    }
    public Set<SolicitudPqr> getSolicitudPqrs() {
        return this.solicitudPqrs;
    }
    
    public void setSolicitudPqrs(Set<SolicitudPqr> solicitudPqrs) {
        this.solicitudPqrs = solicitudPqrs;
    }




}


