package com.tcbuen.pqrs.modelo;
// Generated 20-ago-2014 23:05:43 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MotivoReclamacion generated by hbm2java
 */
public class MotivoReclamacion  implements java.io.Serializable {


     private Long idMotRecl;
     private String descripcionMotRecl;
     private String estadoRegistro;
     private Date fechaCreacion;
     private String usuarioCreador;
     private Date fechaUltimaModificacion;
     private String usuarioUltimaModificacion;
     private Set<MotReclXTpSol> motReclXTpSols = new HashSet<MotReclXTpSol>(0);
     private Set<MotReclSelect> motReclSelects = new HashSet<MotReclSelect>(0);

    public MotivoReclamacion() {
    }

	
    public MotivoReclamacion(Long idMotRecl, String descripcionMotRecl, String estadoRegistro) {
        this.idMotRecl = idMotRecl;
        this.descripcionMotRecl = descripcionMotRecl;
        this.estadoRegistro = estadoRegistro;
    }
    public MotivoReclamacion(Long idMotRecl, String descripcionMotRecl, String estadoRegistro, Date fechaCreacion, String usuarioCreador, Date fechaUltimaModificacion, String usuarioUltimaModificacion, Set<MotReclXTpSol> motReclXTpSols, Set<MotReclSelect> motReclSelects) {
       this.idMotRecl = idMotRecl;
       this.descripcionMotRecl = descripcionMotRecl;
       this.estadoRegistro = estadoRegistro;
       this.fechaCreacion = fechaCreacion;
       this.usuarioCreador = usuarioCreador;
       this.fechaUltimaModificacion = fechaUltimaModificacion;
       this.usuarioUltimaModificacion = usuarioUltimaModificacion;
       this.motReclXTpSols = motReclXTpSols;
       this.motReclSelects = motReclSelects;
    }
   
    public Long getIdMotRecl() {
        return this.idMotRecl;
    }
    
    public void setIdMotRecl(Long idMotRecl) {
        this.idMotRecl = idMotRecl;
    }
    public String getDescripcionMotRecl() {
        return this.descripcionMotRecl;
    }
    
    public void setDescripcionMotRecl(String descripcionMotRecl) {
        this.descripcionMotRecl = descripcionMotRecl;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getUsuarioCreador() {
        return this.usuarioCreador;
    }
    
    public void setUsuarioCreador(String usuarioCreador) {
        this.usuarioCreador = usuarioCreador;
    }
    public Date getFechaUltimaModificacion() {
        return this.fechaUltimaModificacion;
    }
    
    public void setFechaUltimaModificacion(Date fechaUltimaModificacion) {
        this.fechaUltimaModificacion = fechaUltimaModificacion;
    }
    public String getUsuarioUltimaModificacion() {
        return this.usuarioUltimaModificacion;
    }
    
    public void setUsuarioUltimaModificacion(String usuarioUltimaModificacion) {
        this.usuarioUltimaModificacion = usuarioUltimaModificacion;
    }
    public Set<MotReclXTpSol> getMotReclXTpSols() {
        return this.motReclXTpSols;
    }
    
    public void setMotReclXTpSols(Set<MotReclXTpSol> motReclXTpSols) {
        this.motReclXTpSols = motReclXTpSols;
    }
    public Set<MotReclSelect> getMotReclSelects() {
        return this.motReclSelects;
    }
    
    public void setMotReclSelects(Set<MotReclSelect> motReclSelects) {
        this.motReclSelects = motReclSelects;
    }




}


