package com.tcbuen.pqrs.modelo;
// Generated 20-ago-2014 23:05:43 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MotivoSolicitud generated by hbm2java
 */
public class MotivoSolicitud  implements java.io.Serializable {


     private Long idMotSol;
     private String descripcionMotSol;
     private String estadoRegistro;
     private Date fechaCreacion;
     private String usuarioCreador;
     private Date fechaUltimaModificacion;
     private String usuarioUltimaModificacion;
     private Set<MotSolXTpSol> motSolXTpSols = new HashSet<MotSolXTpSol>(0);
     private Set<MotSolSelect> motSolSelects = new HashSet<MotSolSelect>(0);

    public MotivoSolicitud() {
    }

	
    public MotivoSolicitud(Long idMotSol, String descripcionMotSol, String estadoRegistro) {
        this.idMotSol = idMotSol;
        this.descripcionMotSol = descripcionMotSol;
        this.estadoRegistro = estadoRegistro;
    }
    public MotivoSolicitud(Long idMotSol, String descripcionMotSol, String estadoRegistro, Date fechaCreacion, String usuarioCreador, Date fechaUltimaModificacion, String usuarioUltimaModificacion, Set<MotSolXTpSol> motSolXTpSols, Set<MotSolSelect> motSolSelects) {
       this.idMotSol = idMotSol;
       this.descripcionMotSol = descripcionMotSol;
       this.estadoRegistro = estadoRegistro;
       this.fechaCreacion = fechaCreacion;
       this.usuarioCreador = usuarioCreador;
       this.fechaUltimaModificacion = fechaUltimaModificacion;
       this.usuarioUltimaModificacion = usuarioUltimaModificacion;
       this.motSolXTpSols = motSolXTpSols;
       this.motSolSelects = motSolSelects;
    }
   
    public Long getIdMotSol() {
        return this.idMotSol;
    }
    
    public void setIdMotSol(Long idMotSol) {
        this.idMotSol = idMotSol;
    }
    public String getDescripcionMotSol() {
        return this.descripcionMotSol;
    }
    
    public void setDescripcionMotSol(String descripcionMotSol) {
        this.descripcionMotSol = descripcionMotSol;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getUsuarioCreador() {
        return this.usuarioCreador;
    }
    
    public void setUsuarioCreador(String usuarioCreador) {
        this.usuarioCreador = usuarioCreador;
    }
    public Date getFechaUltimaModificacion() {
        return this.fechaUltimaModificacion;
    }
    
    public void setFechaUltimaModificacion(Date fechaUltimaModificacion) {
        this.fechaUltimaModificacion = fechaUltimaModificacion;
    }
    public String getUsuarioUltimaModificacion() {
        return this.usuarioUltimaModificacion;
    }
    
    public void setUsuarioUltimaModificacion(String usuarioUltimaModificacion) {
        this.usuarioUltimaModificacion = usuarioUltimaModificacion;
    }
    public Set<MotSolXTpSol> getMotSolXTpSols() {
        return this.motSolXTpSols;
    }
    
    public void setMotSolXTpSols(Set<MotSolXTpSol> motSolXTpSols) {
        this.motSolXTpSols = motSolXTpSols;
    }
    public Set<MotSolSelect> getMotSolSelects() {
        return this.motSolSelects;
    }
    
    public void setMotSolSelects(Set<MotSolSelect> motSolSelects) {
        this.motSolSelects = motSolSelects;
    }




}


