package com.tcbuen.pqrs.modelo;
// Generated 20-ago-2014 23:05:43 by Hibernate Tools 4.0.0



/**
 * MotSolSelect generated by hbm2java
 */
public class MotSolSelect  implements java.io.Serializable {


     private Long idMotSolSelected;
     private SolicitudPqr solicitudPqr;
     private MotivoSolicitud motivoSolicitud;

    public MotSolSelect() {
    }

    public MotSolSelect(Long idMotSolSelected, SolicitudPqr solicitudPqr, MotivoSolicitud motivoSolicitud) {
       this.idMotSolSelected = idMotSolSelected;
       this.solicitudPqr = solicitudPqr;
       this.motivoSolicitud = motivoSolicitud;
    }
   
    public Long getIdMotSolSelected() {
        return this.idMotSolSelected;
    }
    
    public void setIdMotSolSelected(Long idMotSolSelected) {
        this.idMotSolSelected = idMotSolSelected;
    }
    public SolicitudPqr getSolicitudPqr() {
        return this.solicitudPqr;
    }
    
    public void setSolicitudPqr(SolicitudPqr solicitudPqr) {
        this.solicitudPqr = solicitudPqr;
    }
    public MotivoSolicitud getMotivoSolicitud() {
        return this.motivoSolicitud;
    }
    
    public void setMotivoSolicitud(MotivoSolicitud motivoSolicitud) {
        this.motivoSolicitud = motivoSolicitud;
    }




}


