package com.tcbuen.pqrs.modelo;
// Generated 20-ago-2014 23:05:43 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocumento generated by hbm2java
 */
public class TipoDocumento  implements java.io.Serializable {


     private Long idTpDoc;
     private String descripcionTpDoc;
     private String estadoRegistro;
     private Date fechaCreacion;
     private String usuarioCreador;
     private Date fechaUltimaModificacion;
     private String usuarioUltimaModificacion;
     private Set<InfoSolicitante> infoSolicitantes = new HashSet<InfoSolicitante>(0);

    public TipoDocumento() {
    }

	
    public TipoDocumento(Long idTpDoc, String descripcionTpDoc, String estadoRegistro) {
        this.idTpDoc = idTpDoc;
        this.descripcionTpDoc = descripcionTpDoc;
        this.estadoRegistro = estadoRegistro;
    }
    public TipoDocumento(Long idTpDoc, String descripcionTpDoc, String estadoRegistro, Date fechaCreacion, String usuarioCreador, Date fechaUltimaModificacion, String usuarioUltimaModificacion, Set<InfoSolicitante> infoSolicitantes) {
       this.idTpDoc = idTpDoc;
       this.descripcionTpDoc = descripcionTpDoc;
       this.estadoRegistro = estadoRegistro;
       this.fechaCreacion = fechaCreacion;
       this.usuarioCreador = usuarioCreador;
       this.fechaUltimaModificacion = fechaUltimaModificacion;
       this.usuarioUltimaModificacion = usuarioUltimaModificacion;
       this.infoSolicitantes = infoSolicitantes;
    }
   
    public Long getIdTpDoc() {
        return this.idTpDoc;
    }
    
    public void setIdTpDoc(Long idTpDoc) {
        this.idTpDoc = idTpDoc;
    }
    public String getDescripcionTpDoc() {
        return this.descripcionTpDoc;
    }
    
    public void setDescripcionTpDoc(String descripcionTpDoc) {
        this.descripcionTpDoc = descripcionTpDoc;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getUsuarioCreador() {
        return this.usuarioCreador;
    }
    
    public void setUsuarioCreador(String usuarioCreador) {
        this.usuarioCreador = usuarioCreador;
    }
    public Date getFechaUltimaModificacion() {
        return this.fechaUltimaModificacion;
    }
    
    public void setFechaUltimaModificacion(Date fechaUltimaModificacion) {
        this.fechaUltimaModificacion = fechaUltimaModificacion;
    }
    public String getUsuarioUltimaModificacion() {
        return this.usuarioUltimaModificacion;
    }
    
    public void setUsuarioUltimaModificacion(String usuarioUltimaModificacion) {
        this.usuarioUltimaModificacion = usuarioUltimaModificacion;
    }
    public Set<InfoSolicitante> getInfoSolicitantes() {
        return this.infoSolicitantes;
    }
    
    public void setInfoSolicitantes(Set<InfoSolicitante> infoSolicitantes) {
        this.infoSolicitantes = infoSolicitantes;
    }




}


