package com.tcbuen.pqrs.modelo;
// Generated 20-ago-2014 23:05:43 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoEstadoPqr generated by hbm2java
 */
public class TipoEstadoPqr  implements java.io.Serializable {


     private Long idTpEstPqr;
     private String descripcionEstado;
     private String estadoRegistro;
     private Date fechaCreacion;
     private String usuarioCreador;
     private Date fechaUltimaModificacion;
     private String usuarioUltimaModificacion;
     private Set<SolicitudPqr> solicitudPqrs = new HashSet<SolicitudPqr>(0);

    public TipoEstadoPqr() {
    }

	
    public TipoEstadoPqr(Long idTpEstPqr, String descripcionEstado, String estadoRegistro) {
        this.idTpEstPqr = idTpEstPqr;
        this.descripcionEstado = descripcionEstado;
        this.estadoRegistro = estadoRegistro;
    }
    public TipoEstadoPqr(Long idTpEstPqr, String descripcionEstado, String estadoRegistro, Date fechaCreacion, String usuarioCreador, Date fechaUltimaModificacion, String usuarioUltimaModificacion, Set<SolicitudPqr> solicitudPqrs) {
       this.idTpEstPqr = idTpEstPqr;
       this.descripcionEstado = descripcionEstado;
       this.estadoRegistro = estadoRegistro;
       this.fechaCreacion = fechaCreacion;
       this.usuarioCreador = usuarioCreador;
       this.fechaUltimaModificacion = fechaUltimaModificacion;
       this.usuarioUltimaModificacion = usuarioUltimaModificacion;
       this.solicitudPqrs = solicitudPqrs;
    }
   
    public Long getIdTpEstPqr() {
        return this.idTpEstPqr;
    }
    
    public void setIdTpEstPqr(Long idTpEstPqr) {
        this.idTpEstPqr = idTpEstPqr;
    }
    public String getDescripcionEstado() {
        return this.descripcionEstado;
    }
    
    public void setDescripcionEstado(String descripcionEstado) {
        this.descripcionEstado = descripcionEstado;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getUsuarioCreador() {
        return this.usuarioCreador;
    }
    
    public void setUsuarioCreador(String usuarioCreador) {
        this.usuarioCreador = usuarioCreador;
    }
    public Date getFechaUltimaModificacion() {
        return this.fechaUltimaModificacion;
    }
    
    public void setFechaUltimaModificacion(Date fechaUltimaModificacion) {
        this.fechaUltimaModificacion = fechaUltimaModificacion;
    }
    public String getUsuarioUltimaModificacion() {
        return this.usuarioUltimaModificacion;
    }
    
    public void setUsuarioUltimaModificacion(String usuarioUltimaModificacion) {
        this.usuarioUltimaModificacion = usuarioUltimaModificacion;
    }
    public Set<SolicitudPqr> getSolicitudPqrs() {
        return this.solicitudPqrs;
    }
    
    public void setSolicitudPqrs(Set<SolicitudPqr> solicitudPqrs) {
        this.solicitudPqrs = solicitudPqrs;
    }




}


