package com.tcbuen.pqrs.modelo;
// Generated 20-ago-2014 23:05:43 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoSolicitudPqr generated by hbm2java
 */
public class TipoSolicitudPqr  implements java.io.Serializable {


     private Long idTpSolPqr;
     private String descTpSol;
     private String estadoRegistro;
     private Date fechaCreacion;
     private String usuarioCreador;
     private Date fechaUltimaModificacion;
     private String usuarioUltimaModificacion;
     private Set<AnxsXTpSol> anxsXTpSols = new HashSet<AnxsXTpSol>(0);
     private Set<MotReclXTpSol> motReclXTpSols = new HashSet<MotReclXTpSol>(0);
     private Set<MotSolXTpSol> motSolXTpSols = new HashSet<MotSolXTpSol>(0);
     private Set<SolicitudPqr> solicitudPqrs = new HashSet<SolicitudPqr>(0);

    public TipoSolicitudPqr() {
    }

	
    public TipoSolicitudPqr(Long idTpSolPqr, String descTpSol, String estadoRegistro) {
        this.idTpSolPqr = idTpSolPqr;
        this.descTpSol = descTpSol;
        this.estadoRegistro = estadoRegistro;
    }
    public TipoSolicitudPqr(Long idTpSolPqr, String descTpSol, String estadoRegistro, Date fechaCreacion, String usuarioCreador, Date fechaUltimaModificacion, String usuarioUltimaModificacion, Set<AnxsXTpSol> anxsXTpSols, Set<MotReclXTpSol> motReclXTpSols, Set<MotSolXTpSol> motSolXTpSols, Set<SolicitudPqr> solicitudPqrs) {
       this.idTpSolPqr = idTpSolPqr;
       this.descTpSol = descTpSol;
       this.estadoRegistro = estadoRegistro;
       this.fechaCreacion = fechaCreacion;
       this.usuarioCreador = usuarioCreador;
       this.fechaUltimaModificacion = fechaUltimaModificacion;
       this.usuarioUltimaModificacion = usuarioUltimaModificacion;
       this.anxsXTpSols = anxsXTpSols;
       this.motReclXTpSols = motReclXTpSols;
       this.motSolXTpSols = motSolXTpSols;
       this.solicitudPqrs = solicitudPqrs;
    }
   
    public Long getIdTpSolPqr() {
        return this.idTpSolPqr;
    }
    
    public void setIdTpSolPqr(Long idTpSolPqr) {
        this.idTpSolPqr = idTpSolPqr;
    }
    public String getDescTpSol() {
        return this.descTpSol;
    }
    
    public void setDescTpSol(String descTpSol) {
        this.descTpSol = descTpSol;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getUsuarioCreador() {
        return this.usuarioCreador;
    }
    
    public void setUsuarioCreador(String usuarioCreador) {
        this.usuarioCreador = usuarioCreador;
    }
    public Date getFechaUltimaModificacion() {
        return this.fechaUltimaModificacion;
    }
    
    public void setFechaUltimaModificacion(Date fechaUltimaModificacion) {
        this.fechaUltimaModificacion = fechaUltimaModificacion;
    }
    public String getUsuarioUltimaModificacion() {
        return this.usuarioUltimaModificacion;
    }
    
    public void setUsuarioUltimaModificacion(String usuarioUltimaModificacion) {
        this.usuarioUltimaModificacion = usuarioUltimaModificacion;
    }
    public Set<AnxsXTpSol> getAnxsXTpSols() {
        return this.anxsXTpSols;
    }
    
    public void setAnxsXTpSols(Set<AnxsXTpSol> anxsXTpSols) {
        this.anxsXTpSols = anxsXTpSols;
    }
    public Set<MotReclXTpSol> getMotReclXTpSols() {
        return this.motReclXTpSols;
    }
    
    public void setMotReclXTpSols(Set<MotReclXTpSol> motReclXTpSols) {
        this.motReclXTpSols = motReclXTpSols;
    }
    public Set<MotSolXTpSol> getMotSolXTpSols() {
        return this.motSolXTpSols;
    }
    
    public void setMotSolXTpSols(Set<MotSolXTpSol> motSolXTpSols) {
        this.motSolXTpSols = motSolXTpSols;
    }
    public Set<SolicitudPqr> getSolicitudPqrs() {
        return this.solicitudPqrs;
    }
    
    public void setSolicitudPqrs(Set<SolicitudPqr> solicitudPqrs) {
        this.solicitudPqrs = solicitudPqrs;
    }




}


