package com.tcbuen.pqrs.modelo;
// Generated 20-ago-2014 23:05:43 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * UsuariosInternos generated by hbm2java
 */
public class UsuariosInternos  implements java.io.Serializable {


     private Long idUsuInterno;
     private Roles roles;
     private AreasInvolucradas areasInvolucradas;
     private String numeroIdentificacion;
     private String nombres;
     private String apellidos;
     private String login;
     private String contrasena;
     private String correoElectronico;
     private String estadoRegistro;
     private Date fechaCreacion;

    public UsuariosInternos() {
    }

	
    public UsuariosInternos(Long idUsuInterno, AreasInvolucradas areasInvolucradas, String numeroIdentificacion, String nombres, String apellidos, String login, String contrasena, String estadoRegistro) {
        this.idUsuInterno = idUsuInterno;
        this.areasInvolucradas = areasInvolucradas;
        this.numeroIdentificacion = numeroIdentificacion;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.login = login;
        this.contrasena = contrasena;
        this.estadoRegistro = estadoRegistro;
    }
    public UsuariosInternos(Long idUsuInterno, Roles roles, AreasInvolucradas areasInvolucradas, String numeroIdentificacion, String nombres, String apellidos, String login, String contrasena, String correoElectronico, String estadoRegistro, Date fechaCreacion) {
       this.idUsuInterno = idUsuInterno;
       this.roles = roles;
       this.areasInvolucradas = areasInvolucradas;
       this.numeroIdentificacion = numeroIdentificacion;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.login = login;
       this.contrasena = contrasena;
       this.correoElectronico = correoElectronico;
       this.estadoRegistro = estadoRegistro;
       this.fechaCreacion = fechaCreacion;
    }
   
    public Long getIdUsuInterno() {
        return this.idUsuInterno;
    }
    
    public void setIdUsuInterno(Long idUsuInterno) {
        this.idUsuInterno = idUsuInterno;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public AreasInvolucradas getAreasInvolucradas() {
        return this.areasInvolucradas;
    }
    
    public void setAreasInvolucradas(AreasInvolucradas areasInvolucradas) {
        this.areasInvolucradas = areasInvolucradas;
    }
    public String getNumeroIdentificacion() {
        return this.numeroIdentificacion;
    }
    
    public void setNumeroIdentificacion(String numeroIdentificacion) {
        this.numeroIdentificacion = numeroIdentificacion;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


