package com.tcbuen.pqrs.modelo;
// Generated 20-ago-2014 23:05:43 by Hibernate Tools 4.0.0


import java.sql.Blob;
import java.util.Date;

/**
 * AnexosRespuesta generated by hbm2java
 */
public class AnexosRespuesta  implements java.io.Serializable {


     private Long idAnxResp;
     private RespuestaSol respuestaSol;
     private AnexosPqr anexosPqr;
     private Blob documentoReal;
     private String nombreAnexo;
     private String nombreBusqueda;
     private String adjuntoDocumento;
     private String estadoRegistro;
     private Date fechaCreacion;
     private String usuarioCreador;

    public AnexosRespuesta() {
    }

	
    public AnexosRespuesta(Long idAnxResp, RespuestaSol respuestaSol, AnexosPqr anexosPqr, String nombreAnexo, String nombreBusqueda, String estadoRegistro) {
        this.idAnxResp = idAnxResp;
        this.respuestaSol = respuestaSol;
        this.anexosPqr = anexosPqr;
        this.nombreAnexo = nombreAnexo;
        this.nombreBusqueda = nombreBusqueda;
        this.estadoRegistro = estadoRegistro;
    }
    public AnexosRespuesta(Long idAnxResp, RespuestaSol respuestaSol, AnexosPqr anexosPqr, Blob documentoReal, String nombreAnexo, String nombreBusqueda, String adjuntoDocumento, String estadoRegistro, Date fechaCreacion, String usuarioCreador) {
       this.idAnxResp = idAnxResp;
       this.respuestaSol = respuestaSol;
       this.anexosPqr = anexosPqr;
       this.documentoReal = documentoReal;
       this.nombreAnexo = nombreAnexo;
       this.nombreBusqueda = nombreBusqueda;
       this.adjuntoDocumento = adjuntoDocumento;
       this.estadoRegistro = estadoRegistro;
       this.fechaCreacion = fechaCreacion;
       this.usuarioCreador = usuarioCreador;
    }
   
    public Long getIdAnxResp() {
        return this.idAnxResp;
    }
    
    public void setIdAnxResp(Long idAnxResp) {
        this.idAnxResp = idAnxResp;
    }
    public RespuestaSol getRespuestaSol() {
        return this.respuestaSol;
    }
    
    public void setRespuestaSol(RespuestaSol respuestaSol) {
        this.respuestaSol = respuestaSol;
    }
    public AnexosPqr getAnexosPqr() {
        return this.anexosPqr;
    }
    
    public void setAnexosPqr(AnexosPqr anexosPqr) {
        this.anexosPqr = anexosPqr;
    }
    public Blob getDocumentoReal() {
        return this.documentoReal;
    }
    
    public void setDocumentoReal(Blob documentoReal) {
        this.documentoReal = documentoReal;
    }
    public String getNombreAnexo() {
        return this.nombreAnexo;
    }
    
    public void setNombreAnexo(String nombreAnexo) {
        this.nombreAnexo = nombreAnexo;
    }
    public String getNombreBusqueda() {
        return this.nombreBusqueda;
    }
    
    public void setNombreBusqueda(String nombreBusqueda) {
        this.nombreBusqueda = nombreBusqueda;
    }
    public String getAdjuntoDocumento() {
        return this.adjuntoDocumento;
    }
    
    public void setAdjuntoDocumento(String adjuntoDocumento) {
        this.adjuntoDocumento = adjuntoDocumento;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getUsuarioCreador() {
        return this.usuarioCreador;
    }
    
    public void setUsuarioCreador(String usuarioCreador) {
        this.usuarioCreador = usuarioCreador;
    }




}


