package com.tcbuen.pqrs.modelo;
// Generated 20-ago-2014 23:05:43 by Hibernate Tools 4.0.0



/**
 * MotSolXTpSol generated by hbm2java
 */
public class MotSolXTpSol  implements java.io.Serializable {


     private Long idMotSolXTpSol;
     private TipoSolicitudPqr tipoSolicitudPqr;
     private MotivoSolicitud motivoSolicitud;

    public MotSolXTpSol() {
    }

    public MotSolXTpSol(Long idMotSolXTpSol, TipoSolicitudPqr tipoSolicitudPqr, MotivoSolicitud motivoSolicitud) {
       this.idMotSolXTpSol = idMotSolXTpSol;
       this.tipoSolicitudPqr = tipoSolicitudPqr;
       this.motivoSolicitud = motivoSolicitud;
    }
   
    public Long getIdMotSolXTpSol() {
        return this.idMotSolXTpSol;
    }
    
    public void setIdMotSolXTpSol(Long idMotSolXTpSol) {
        this.idMotSolXTpSol = idMotSolXTpSol;
    }
    public TipoSolicitudPqr getTipoSolicitudPqr() {
        return this.tipoSolicitudPqr;
    }
    
    public void setTipoSolicitudPqr(TipoSolicitudPqr tipoSolicitudPqr) {
        this.tipoSolicitudPqr = tipoSolicitudPqr;
    }
    public MotivoSolicitud getMotivoSolicitud() {
        return this.motivoSolicitud;
    }
    
    public void setMotivoSolicitud(MotivoSolicitud motivoSolicitud) {
        this.motivoSolicitud = motivoSolicitud;
    }




}


