package com.tcbuen.pqrs.modelo;
// Generated 20-ago-2014 23:05:43 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SolicitudAsignadaArea generated by hbm2java
 */
public class SolicitudAsignadaArea  implements java.io.Serializable {


     private Long idSolAsigArea;
     private SolicitudPqr solicitudPqr;
     private AreasInvolucradas areasInvolucradas;
     private Date fechaAsignacion;
     private Date fechaRespuesta;
     private Set<RespuestaSol> respuestaSols = new HashSet<RespuestaSol>(0);

    public SolicitudAsignadaArea() {
    }

	
    public SolicitudAsignadaArea(Long idSolAsigArea, Date fechaAsignacion) {
        this.idSolAsigArea = idSolAsigArea;
        this.fechaAsignacion = fechaAsignacion;
    }
    public SolicitudAsignadaArea(Long idSolAsigArea, SolicitudPqr solicitudPqr, AreasInvolucradas areasInvolucradas, Date fechaAsignacion, Date fechaRespuesta, Set<RespuestaSol> respuestaSols) {
       this.idSolAsigArea = idSolAsigArea;
       this.solicitudPqr = solicitudPqr;
       this.areasInvolucradas = areasInvolucradas;
       this.fechaAsignacion = fechaAsignacion;
       this.fechaRespuesta = fechaRespuesta;
       this.respuestaSols = respuestaSols;
    }
   
    public Long getIdSolAsigArea() {
        return this.idSolAsigArea;
    }
    
    public void setIdSolAsigArea(Long idSolAsigArea) {
        this.idSolAsigArea = idSolAsigArea;
    }
    public SolicitudPqr getSolicitudPqr() {
        return this.solicitudPqr;
    }
    
    public void setSolicitudPqr(SolicitudPqr solicitudPqr) {
        this.solicitudPqr = solicitudPqr;
    }
    public AreasInvolucradas getAreasInvolucradas() {
        return this.areasInvolucradas;
    }
    
    public void setAreasInvolucradas(AreasInvolucradas areasInvolucradas) {
        this.areasInvolucradas = areasInvolucradas;
    }
    public Date getFechaAsignacion() {
        return this.fechaAsignacion;
    }
    
    public void setFechaAsignacion(Date fechaAsignacion) {
        this.fechaAsignacion = fechaAsignacion;
    }
    public Date getFechaRespuesta() {
        return this.fechaRespuesta;
    }
    
    public void setFechaRespuesta(Date fechaRespuesta) {
        this.fechaRespuesta = fechaRespuesta;
    }
    public Set<RespuestaSol> getRespuestaSols() {
        return this.respuestaSols;
    }
    
    public void setRespuestaSols(Set<RespuestaSol> respuestaSols) {
        this.respuestaSols = respuestaSols;
    }




}


